### ISSUE TITLE
Text-editor does not shows changements in Webdav Saved File

### ISSUE THREAD

**Issue by Yamakasi** [owncloud/files_texteditor#106] opened 2015-09-06 16:28 UTC
When I open a odt file from webdav and I save it this happens:

/index.php/apps/files/ajax/download.php?dir=%2FDocuments&files=Example.odt has the updated version (this is the file explorer and also show versioning from the explorer)

/index.php/apps/documents/#15 has the base content from the first start of the file. (this is the fileEditor)

It seems that the fileeditor does not index right ?

**Comment by RealRancor** [comment] 2015-09-06 17:51
Seems to me as a duplicate of https://github.com/owncloud/documents/issues/447

**Closed** 2015-09-06 20:26 UTC
