### ISSUE TITLE
New Lines are ignored on Windows

### ISSUE THREAD

**Issue by MorrisJobke** [owncloud/files_texteditor#60] opened 2015-02-10 15:30 UTC
On Windows when creating a text-file in the browser and then open it locally in Notepad, new lines are ignored.

### Steps to reproduce
Tested on Windows 7 with IE 11 on ownCloud Server 6 with client 1.7.1  and ownCloud Server 7  with ownCloud client 1.7.1 :
1. go to the browser and create a text-file.
2. edit the newly created text-file and write on multiple lines. ie.
		"hi
		there
		how
		are
		you"
3. wait to sync on your windows computer
4. open the text-file in notepad.exe

### Expected Result:
		"hi
		there
		how
		are
		you"

### Actual Result:
		"hitherehowareyou"

The newlines are completely ignored. This is a problem all Windows user have.

@MorrisJobke 

00002575

from  https://github.com/owncloud/core/issues/14046 by @cdamken

**Comment by tomneedham** [comment] 2015-02-14 14:52
My knowledge of encoding is limited here, but on doing some reading I believe it comes down to how Notepad interprets newline characters. Notepad requires CR AND LF, whereas by default Unix is happy with just LF, and this is what the text editors saves as.

On the other hand, Wordpad (also installed by default on Windows) will handle just LF correctly.

I can try using this: http://ace.c9.io/api/document.html#Document.setNewLineMode to force Ace to insert windows style line endings, but need to test how this affects unix.

**Comment by tomneedham** [comment] 2015-02-27 18:14
@MorrisJobke

**Comment by MorrisJobke** [comment] 2015-02-27 19:04
It's always bad to decide on this for the user. ... @owncloud/designers for this UX question

**Comment by tomneedham** [comment] 2015-03-01 22:11
@MorrisJobke If I understand correctly we can set the new line mode within Ace to 'windows' and this should fix the issue on Windows and still work as intended on unix. Let me test this.

**Comment by tomneedham** [comment] 2015-03-01 22:50
Tested this. If we set the line endings to 'windows' they are correctly interpreted by unix and windows (including Notepad) editors. Maybe this is a safer default? Thoughts here @DeepDiver1975 and @MorrisJobke

**Comment by MorrisJobke** [comment] 2015-03-02 07:36
@tomneedham This sounds like a reasonable work around. And usually all editors on Mac/Linux also know the Windows line break format. So there shouldn't be any problem.

**Comment by DeepDiver1975** [comment] 2015-03-02 09:19
> On Windows when creating a text-file in the browser and then open it locally in Notepad, new lines are ignored.

seriously - notepad is a piece of shit editor - we will not add any kind of line ending conversions.
This is nightmare already on version control systems.

I vote for 'Won't fix'

**Comment by jancborchardt** [comment] 2015-03-02 13:24
Does it only happen with Notepad though? If we can just set another line ending mode in Ace and it’s fixed with that, let’s do it.

**Comment by PVince81** [comment] 2015-03-02 13:27
The question here is if you change the line ending in ACE regardless of OS, when I save the file, will it still have UNIX endings or will ACE convert all my text files to DOS on save ? (which is not acceptable)

**Comment by tomneedham** [comment] 2015-03-02 13:30
> Does it only happen with Notepad though?

Yes. Even with Wordpad on Windows it works fine.



> will it still have UNIX endings or will ACE convert all my text files to DOS on save

I believe the setting only influences 'new lines' made inside of Ace. https://github.com/owncloud/files_texteditor/commit/042b0734ccf7df66cdccaa998eb4b58d46a0664a

Let me test this.

**Comment by nickvergessen** [comment] 2015-03-05 13:36
> I vote for 'Won't fix'

same here. The solution is use something that is not stupid on windows to edit files.
All source code files are one liners in this stupid so called "editor".
Not worth any troubles, or even breaking files. The user enters `\n` by pressing enter in the editor window. So he wants a normal line break. We can't blindly guess whether one user will open the file with a crappy editor or a decent one.

**Comment by enoch85** [comment] 2015-03-05 20:34
Related #14268

**Comment by DeepDiver1975** [comment] 2015-03-06 09:15
@enoch85 no - totally unrelated

**Comment by jancborchardt** [comment] 2015-03-06 15:38
@MorrisJobke so what do you think? Do you agree with "Won’t fix"?

**Comment by MorrisJobke** [comment] 2015-03-06 15:43
@jancborchardt Yes. @cdamken Did you understand the solution for this?

**Closed** 2015-03-06 16:17 UTC
Labels: blue-ticket, bug

**Comment by cdamken** [comment] 2015-03-11 14:11
@MorrisJobke Yes, I understand the solution.

#### Thank you all
