### ISSUE TITLE
Clicking outside of the texteditor should also close it

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/files_texteditor#103] opened 2015-09-02 23:31 UTC
And of course save the content, just like when pressing the x on the top right. @tomneedham @owncloud/designers

**Comment by tomneedham** [comment] 2015-11-11 11:15
Duplicate of https://github.com/owncloud/files_texteditor/issues/132

**Closed by tomneedham** 2015-11-11 11:15 UTC
Labels: enhancement

**Comment by jancborchardt** [comment] 2015-11-11 14:49
@tomneedham THAT’S how much I want it. ;)
