### ISSUE TITLE
[Files_external] Using a SFTP mountpoint without edit permission in some files, files_texteditor can make 'fake saves'

### ISSUE THREAD

**Issue by davitol** [owncloud/files_texteditor#155] opened 2015-12-10 10:15 UTC
### Steps to reproduce

1. Configure a files_external mount point SFTP with a backend user WITHOUT 'can edit' permission in some files
2. Go to the files view and browse into the mountpoint

### Expected behaviour

The files without permissions cannot be edited

### Actual behaviour

The files seems to be edited, even 'Saved' message is shown, but checking for the changes they are not saved (right behaviour)

### Server configuration
**Operating system**: ubuntu 14.04

**Web server:** apache 2.4.7

**Database:** mysql

**PHP version:** 5.5.9

**ownCloud version: ownCloud Enterprise Edition 9.0 pre alpha (daily)

**Updated from an older ownCloud or fresh install:** Fresh install

**Are you using external storage, if yes which one:** no;
**Are you using encryption:** no
**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Firefox

**Comment by tomneedham** [comment] 2015-12-18 11:42
Thanks @davitol. Could you see what the value of 'writeable' is in the load ajax response when you first load the file. If this is false then the editor shouldnt be allowing saves in the UI but perhaps it's not getting that information through.
https://github.com/owncloud/files_texteditor/blob/master/controller/filehandlingcontroller.php#L89

**Comment by tomneedham** [comment] 2015-12-30 10:26
@davitol Trying to dig into this, can you explain your external storage setup in a bit more detail so I can replicate it? Is it system or user level mount?

**Comment by tomneedham** [comment] 2015-12-30 10:32
Ah reproduced it I think. I have a user level mount to a folder where the sftp user does not have write permissions to all of the files yet the editors `load file` route returns 'writeable' as true, hence it lets the editor edit files. Still digging

**Comment by tomneedham** [comment] 2015-12-30 10:34
So the issue is with the file view returning isUpdatable as true herehttps://github.com/owncloud/files_texteditor/blob/master/controller/filehandlingcontroller.php#L89

**Comment by tomneedham** [comment] 2015-12-30 11:18
Soo I believe this is because the SFTP backend does not specifically implement isUpdatable() which the editor uses to determine if we can write to a file, so instead, the filesystem default to just checking if the file exists as assuming it is writeable if it exists.

SFTP Backend: https://github.com/owncloud/core/blob/master/apps/files_external/lib/sftp.php
And the default/common storage it extends: https://github.com/owncloud/core/blob/master/lib/private/files/storage/common.php#L121

@PVince81 Who can help out with the storage backend stuff here? Should we implement isUpdatable()? From reading we would have to use stat() on the file and read the mode. Not sure how solid this is as a method.

Tricky thing from the UI perspective is the editor will always allow editing as it has no idea about the file permissions, so it will allow these 'fake saves' but obviously they will always fail. We could improve the feedback here a bit but ideally we get the know the real file permissions.

**Comment by PVince81** [comment] 2016-01-07 10:19
@tomneedham can you make a ticket in core to implement `isUpdatable` properly for SFTP ?
I believe that `getPermissions()` already does a `stat()` so it might be possible to get the permission from there.

CC @Xenopathic

**Comment by PVince81** [comment] 2016-10-20 16:10
closing as duplicate of https://github.com/owncloud/core/issues/21526

**Closed by PVince81** 2016-10-20 16:10 UTC
Labels: bug, sev3-medium
